# k8s/haproxy-cert.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: haproxy-cert
  namespace: ingress-controller
spec:
  secretName: haproxy-tls
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  subject:
    organizations:
      - WSP Lab
  commonName: "*.wsp.local"
  dnsNames:
    - "*.wsp.local"
    - "wsp.local"
  issuerRef:
    name: wsp-intermediate-ca
    kind: ClusterIssuer

