apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-test-config
  namespace: nginx-test
data:
  nginx.conf: |
    daemon off;
    worker_processes auto;
    error_log stderr debug;
    pid /usr/local/openresty/nginx/logs/nginx.pid;

    events {
        worker_connections 1024;
    }

    http {
        include /usr/local/openresty/nginx/conf/mime.types;
        default_type application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                         '$status $body_bytes_sent "$http_referer" '
                         '"$http_user_agent" "$http_x_forwarded_for"';

        access_log /dev/stdout main;

        # Temp paths
        client_body_temp_path /tmp/openresty/client_temp;
        proxy_temp_path       /tmp/openresty/proxy_temp;
        fastcgi_temp_path    /tmp/openresty/fastcgi_temp;
        uwsgi_temp_path      /tmp/openresty/uwsgi_temp;
        scgi_temp_path       /tmp/openresty/scgi_temp;

        # Lua settings
        lua_package_path '/usr/local/openresty/lualib/?.lua;;';
        lua_shared_dict discovery 1m;
        lua_shared_dict jwks 1m;
        lua_shared_dict sessions 10m;

        server {
            listen 8080;
            server_name localhost;

            location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;
            }

            location /health {
                access_log off;
                return 200 "healthy\n";
            }

            location = /debug {
                access_log on;
                default_type application/json;
                content_by_lua_block {
                    ngx.say(require("cjson").encode({
                        headers = ngx.req.get_headers(),
                        uri = ngx.var.uri,
                        method = ngx.req.get_method()
                    }))
                }
            }
        }
    }
  mime.types: |
    types {
        text/html                             html htm shtml;
        text/css                              css;
        text/xml                              xml;
        image/gif                             gif;
        image/jpeg                            jpeg jpg;
        application/javascript                js;
        application/json                      json;
        application/xml                       rss atom;
        image/png                             png;
        image/svg+xml                         svg svgz;
        image/webp                            webp;
        image/x-icon                          ico;
        video/mp4                             mp4;
        application/x-font-ttf                ttf;
        application/x-font-woff               woff;
        application/font-woff2                woff2;
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  namespace: nginx-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      securityContext:
        fsGroup: 65534  # nobody group
        runAsUser: 65534  # nobody user
        runAsGroup: 65534  # nobody group
      containers:
      - name: nginx
        image: k3d-registry.localhost:5000/custom-nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /usr/local/openresty/nginx/conf
        - name: temp
          mountPath: /tmp/openresty
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: config
        configMap:
          name: nginx-test-config
          defaultMode: 0644
      - name: temp
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test
  namespace: nginx-test
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: nginx-test