# k8s/nginx-test.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-test-config
  namespace: nginx-test
data:
  nginx.conf: |
    events {
      worker_connections  1024;
    }
    http {
      server {
        listen 80;
        server_name localhost;

        location / {
          auth_request /auth;
          auth_request_set $auth_status $upstream_status;

          root   /usr/share/nginx/html;
          index  index.html index.htm;
        }

        location = /auth {
          internal;
          proxy_pass http://keycloak-test.keycloak-test.svc.cluster.local:8080/realms/master/protocol/openid-connect/auth;
          proxy_pass_request_body off;
          proxy_set_header Content-Length "";
          proxy_set_header X-Original-URI $request_uri;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  namespace: nginx-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: config
        configMap:
          name: nginx-test-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test
  namespace: nginx-test
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx-test