# k8s/test-cert.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-cert
  namespace: default
spec:
  secretName: test-cert-tls
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  subject:
    organizations:
      - WSP Lab
  commonName: test.wsp.local
  dnsNames:
    - test.wsp.local
  issuerRef:
    name: wsp-intermediate-ca
    kind: ClusterIssuer