apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: keycloak
servers: 1
kubeAPI:
  hostIP: "0.0.0.0"
  hostPort: "6444"
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
  runtime:
    serversMemory: "4096m"
    serversCPU: "2"
registries:
  use:
    - k3d-registry.localhost:5111
  config: |
    mirrors:
      "k3d-registry.localhost:5111":
        endpoints:
          - "http://k3d-registry.localhost:5111"
        insecure: true